import Head from "next/head";
import {Row, Col} from "reactstrap";
import WelcomeStyles from "../Assets/Welcome/WelcomeStyle";

import {useRouter} from "next/router";
export default function Home() {
  const router = useRouter();
  return (
    <WelcomeStyles>
      <Head>
        <title>TuCommers</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
        <nav className="nav_container">
          <div className=" row m-0">
            <Col className="col-3 title">
              <span> TuCommers</span>{" "}
            </Col>
            <Col className="col-6 col_container title">
              <div className="menu">
                {" "}
                <div>
                  <p>Nosotros </p>
                </div>
                <div>
                  <p>Proceso</p>
                </div>
                <div>
                  <p>Testimonio</p>
                </div>
                <div>
                  <p>Precios</p>
                </div>
              </div>
            </Col>
            <Col className="col_container col-3">
              <button
                onClick={() => {
                  router.push("/login");
                }}
                className="button-custom button-blue-outline"
              >
                Ingresar
              </button>
              <button
                onClick={() => {
                  router.push("/register");
                }}
                className="button-custom button-blue"
              >
                Registrate
              </button>
            </Col>
          </div>
        </nav>
        <div className="container-all">
          <div className="container-text">
            <p className="text-title">
              Vende tus productos de la mejor manera.
            </p>
            <p className="text-subtitle">
              TuCommers te permite llevar tu negocio al siguiente nivel.
            </p>
          </div>
        </div>
        <img src="./main3.jpg" />
      </main>
      {/*
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </WelcomeStyles>
  );
}
