import Head from "next/head";
import {Row, Col} from "reactstrap";
import styles from "../Assets/Welcome/Welcome.module.scss";
import Image from "next/image";

import {useRouter} from "next/router";
export default function Home() {
  const router = useRouter();
  return (
    <div>
      <nav className={`${styles.nav_container}`}>
        <Row className={styles.container}>
          <Col className={styles.col_container}>
            <Image width={300} height={50} src="/logo.jpg" alt="" />
          </Col>
          <Col className={styles.menu}>
            <div>
              <p>Nosotros</p>
            </div>
            <div>
              <p>Proceso</p>
            </div>
            <div>
              <p>Testimonio</p>
            </div>
            <div>
              <p>Precios</p>
            </div>
          </Col>
          <Col className={styles.col_container}>
            <button
              onClick={() => {
                router.push("/Login");
              }}
              className="button-custom button-blue-outline"
            >
              Ingresar
            </button>
            <button className="button-custom button-blue">Registrate</button>
          </Col>
        </Row>
      </nav>

      <Head>
        <title>TuCommers</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}></main>
      {/*
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  );
}
