import Head from "next/head";

import Navbar from "../Components/Welcome/Navbar/Navbar"
export default function Home() {


  return (
    <div className="welcome-container">
      <Head>
        <title>TuCommers</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
        <Navbar />
        <div className="container-all">
          <div className="container-text">
            <p className="text-title">
              Vende tus productos de la mejor manera.
            </p>
            <p className="text-subtitle">
              TuCommers te permite llevar tu negocio al siguiente nivel.
            </p>
          </div>
        </div>
        <img src="./main3.jpg" />
      </main>
      {/*
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  );
}
